<?php

namespace Database\Seeders;

use App\Models\Plan;
use Illuminate\Database\Seeder;

class PlanSeeder extends Seeder
{
    public function run(): void
    {
        Plan::upsert([
            [
                'name' => 'Free',
                'slug' => 'free',
                'price' => 0,
                'billing_period' => 'monthly',
                'features' => json_encode(['Auto-Reply Keyword']),
                'max_sessions' => 1,
                'max_contacts' => 100,
                'max_autoreplies' => 10,
                'max_campaign_recipients' => 50,
                'can_manage_server' => false,
                'can_use_meta' => true,
                'can_use_forms' => false,
                'can_use_calling' => false,
                'can_use_instagram' => false,
                'can_use_flow' => false,
                'can_use_ai_agent' => false,
                'can_use_intent' => false,
                'can_use_drip' => false,
                'can_use_ab_test' => false,
                'can_use_catalog' => false,
                'can_use_commerce' => false,
                'can_use_deals' => false,
                'can_use_kanban' => false,
                'max_meta_accounts' => 1,
                'max_forms' => 0,
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Growth',
                'slug' => 'growth',
                'price' => 150000,
                'billing_period' => 'monthly',
                'features' => json_encode(['Auto-Reply Keyword', 'Import CSV', 'API Access', 'Webhook', 'Flow Builder', 'Meta API', 'WA Forms', 'Commerce']),
                'max_sessions' => 3,
                'max_contacts' => 5000,
                'max_autoreplies' => 50,
                'max_campaign_recipients' => 1000,
                'can_manage_server' => false,
                'can_use_meta' => true,
                'can_use_forms' => true,
                'can_use_calling' => true,
                'can_use_instagram' => true,
                'can_use_flow' => true,
                'can_use_ai_agent' => true,
                'can_use_intent' => true,
                'can_use_drip' => true,
                'can_use_ab_test' => true,
                'can_use_catalog' => true,
                'can_use_commerce' => true,
                'can_use_deals' => true,
                'can_use_kanban' => true,
                'max_meta_accounts' => 2,
                'max_forms' => 10,
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Enterprise',
                'slug' => 'enterprise',
                'price' => 500000,
                'billing_period' => 'monthly',
                'features' => json_encode(['Auto-Reply Keyword', 'Import CSV', 'API Access', 'Webhook', 'Flow Builder', 'Whitelabel', 'Reseller', 'Priority Support', 'Meta API', 'WA Calling', 'Instagram', 'CRM Deals']),
                'max_sessions' => 10,
                'max_contacts' => 50000,
                'max_autoreplies' => 200,
                'max_campaign_recipients' => 10000,
                'can_manage_server' => true,
                'can_use_meta' => true,
                'can_use_forms' => true,
                'can_use_calling' => true,
                'can_use_instagram' => true,
                'can_use_flow' => true,
                'can_use_ai_agent' => true,
                'can_use_intent' => true,
                'can_use_drip' => true,
                'can_use_ab_test' => true,
                'can_use_catalog' => true,
                'can_use_commerce' => true,
                'can_use_deals' => true,
                'can_use_kanban' => true,
                'max_meta_accounts' => 5,
                'max_forms' => 50,
                'is_active' => true,
                'sort_order' => 3,
            ],
        ], ['slug'], [
            'name', 'price', 'features', 'max_sessions', 'max_contacts',
            'max_autoreplies', 'max_campaign_recipients', 'can_manage_server',
            'can_use_meta', 'can_use_forms', 'can_use_calling', 'can_use_instagram',
            'can_use_flow', 'can_use_ai_agent', 'can_use_intent', 'can_use_drip',
            'can_use_ab_test', 'can_use_catalog', 'can_use_commerce', 'can_use_deals',
            'can_use_kanban', 'max_meta_accounts', 'max_forms',
        ]);
    }
}
